networks:
  jgravalo-dockernet:
    name: jgravalo-dockernet
    driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: .requirements/mariadb
    image: nginx
    restart: always
    networks:
      - jgravalo-dockernet

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - jgravalo-dockernet

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jgravalo/data/mysql
      o: bind
